AWSTemplateFormatVersion: 2010-09-09
Description: Template to Provision GSR Schema operation pipeline

Parameters:
  CodeCommitRepoName:
    Type: String
    Description: Name of the CodeCommit Repo
    Default: schema-customer
  CodeArtifactDomainName:
    Type: String
    Description: Name of the CodeArtifact Domain
    Default: gsr-schema-domain
  CodeArtifactRepositoryName:
    Type: String
    Description: Name of the CodeArtifactRepository
    Default: gsr-schema-mvn-repo
  S3Bucket:
    Type: String
    Description: S3 Bucket containing schema & code
    Default: gsr-schema-pipeline-940270119111
  CustomerSchemaCodeKey:
    Type: String
    Description: Key of zipped code that would be checked in CodeCommit repo
    Default: customer_schema/schema_customer.zip
  CodeCommitTriggerLambdaCodeKey:
    Type: String
    Description: Key of lambda zipped code that would be triggered by CodeCommit events
    Default: codecommit-trigger/codecommit_lambda.zip
  EventRuleLambdaCodeKey:
    Type: String
    Description: Key of lambda zipped code that would be triggered by CodeCommit events
    Default: codebuild-notification/eventrule_lambda.zip
  CodeBuildStateSNSTopicName:
    Type: String
    Description: SNS Topic to receive CodeBuild build status
    Default: gsr-schema-notification
  YourEmail:
    Type: String
    Description: Email to receieve notification
    AllowedPattern : (^[a-zA-Z0-9_.+-]+@[a-zA-Z0-9-]+\.[a-zA-Z0-9-.]+$)
    ConstraintDescription: Must be a valid email address
  AvroFilePath:
    Type: String
    Description: Avro file path in CodeCommit repo
    Default: src/main/resources/avro/
  ManifestFilePath:
    Type: String
    Description: Manifest filename full path in CodeCommit repo
    Default: manifest.yml
  GlueSchemaRegistryName:
    Type: String
    Description: Name of Glue Schema Registry
    Default: enterprise_schemas

Resources:
  GlueSchemaRegistry:
    Type: AWS::Glue::Registry
    Properties: 
      Description: Glue Schema Registry to store all origanisation schemas
      Name: !Ref GlueSchemaRegistryName

  CodeCommitRepo:
    Type: AWS::CodeCommit::Repository
    Properties:
      RepositoryName: !Ref CodeCommitRepoName
      Code:
        BranchName: master
        S3: 
          Bucket: !Ref S3Bucket
          Key: !Ref CustomerSchemaCodeKey
      Triggers: 
        - Name: CodeCommitLambdaTrigger
          DestinationArn: !GetAtt  CodeCommitLambdaTrigger.Arn
          Branches:
            - master
          Events:
            - updateReference
  
  CodeArtifactDomain:
    Type: AWS::CodeArtifact::Domain
    Properties:
      DomainName: !Ref CodeArtifactDomainName
  
  CodeArtifactRepository:
    Type: AWS::CodeArtifact::Repository
    Properties:
      RepositoryName: !Ref CodeArtifactRepositoryName
      DomainName: !GetAtt CodeArtifactDomain.Name

  CodeBuildProject:
    Type: AWS::CodeBuild::Project
    Properties:
      Description: CodeBuild pipeline to serialise schema
      Name: !Sub ${AWS::StackName}-gsr-schema-build
      ServiceRole: !GetAtt CodeBuildRole.Arn
      Artifacts:
        Type: NO_ARTIFACTS
      Cache:
        Location: !Ref S3Bucket
        Type: S3
      Environment:
        Type: LINUX_CONTAINER
        ComputeType: BUILD_GENERAL1_SMALL
        Image: aws/codebuild/amazonlinux2-x86_64-standard:4.0
      Source:
        Type: CODECOMMIT
        Location: !Sub https://git-codecommit.${AWS::Region}.amazonaws.com/v1/repos/${CodeCommitRepoName}
        BuildSpec: buildspec.yml
        GitCloneDepth: 1
      SourceVersion: refs/heads/master
      TimeoutInMinutes: 10
      LogsConfig: 
        CloudWatchLogs:
          GroupName: gsr-schema-build
          Status: ENABLED

  CodeBuildRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
        - Action: ['sts:AssumeRole']
          Effect: Allow
          Principal:
            Service: [codebuild.amazonaws.com]
        Version: '2012-10-17'
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AWSCodeCommitPowerUser
        - arn:aws:iam::aws:policy/AmazonS3ReadOnlyAccess
      Path: /
      Policies:
        - PolicyName: !Sub ${AWS::StackName}-CodeBuildAccess
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Sid: BearerTokenPolicy
                Action:
                  - sts:GetServiceBearerToken
                Effect: Allow
                Resource: '*'
                Condition:
                  StringEquals:
                    sts:AWSServiceName: codeartifact.amazonaws.com
              - Sid: CodeArtifactPolicy
                Effect: Allow
                Action:
                  - codeartifact:GetAuthorizationToken
                Resource:
                  - !Sub "arn:aws:codeartifact:${AWS::Region}:${AWS::AccountId}:domain/${CodeArtifactDomain.Name}"
              - Sid: CodeArtifactPackage
                Action:
                  - codeartifact:ReadFromRepository
                  - codeartifact:PublishPackageVersion
                  - codeartifact:PutPackageMetadata
                Effect: Allow
                Resource: 
                  - !Sub "arn:aws:codeartifact:${AWS::Region}:${AWS::AccountId}:package/${CodeArtifactDomain.Name}/${CodeArtifactRepository.Name}/*"
              - Sid: CodeArtifactRepository
                Effect: Allow
                Action:
                  - codeartifact:ReadFromRepository
                  - codeartifact:GetRepositoryEndpoint
                Resource:
                  - !Sub "arn:aws:codeartifact:${AWS::Region}:${AWS::AccountId}:repository/${CodeArtifactDomain.Name}/${CodeArtifactRepository.Name}"          
              - Sid: CloudWatchLogsPolicy
                Action:
                  - logs:CreateLogGroup
                  - logs:DescribeLogGroups
                  - logs:CreateLogStream
                  - logs:DescribeLogStreams
                  - logs:PutLogEvents
                Effect: Allow
                Resource: !Sub 'arn:aws:logs:${AWS::Region}:${AWS::AccountId}:log-group:*'
              - Sid: S3GetObjectPolicy
                Action:
                  - s3:PutObject
                  - s3:GetObject
                  - s3:GetObjectVersion
                Effect: Allow
                Resource:
                - !Join
                  - ''
                  - - 'arn:aws:s3:::'
                    - !Ref 'S3Bucket'
                - !Join
                  - ''
                  - - 'arn:aws:s3:::'
                    - !Ref 'S3Bucket'
                    - /*          
              - Sid: CloudwatchEventsPolicy
                Action:
                  - iam:PassRole
                Effect: Allow
                Resource: !Sub 'arn:aws:iam::${AWS::AccountId}:role/${AWS::StackName}-CodeBuildRole-*'
                Condition:
                  StringEquals:
                    iam:PassedToService: events.amazonaws.com
  
  CodeCommitLambdaTrigger:
    Type: AWS::Lambda::Function
    DependsOn: CodeCommitLambdaTriggerRole
    Properties:
      Code:
        S3Bucket: !Ref S3Bucket
        S3Key: !Ref CodeCommitTriggerLambdaCodeKey
      Description: Lambda function that will recieve CodeCommit events and will trigger CodeBuild docker image build job.
      FunctionName: !Sub ${CodeBuildProject}-lambda-trigger
      Handler: lambda_function.lambda_handler
      MemorySize: 512
      Role: !GetAtt CodeCommitLambdaTriggerRole.Arn
      Runtime: python3.9
      Timeout: 300
      Environment:
        Variables:
          CODE_BUILD_PROJECT: !Ref CodeBuildProject
          AVRO_FILE_PATH: !Ref AvroFilePath
          MANIFEST_FILE_PATH: !Ref ManifestFilePath
  
  CodeCommitLambdaTriggerRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Action: sts:AssumeRole
            Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
        Version: '2012-10-17'
      Path: /
      Policies:
        - PolicyDocument:
            Statement:
              - Action:
                  - logs:CreateLogGroup
                  - logs:DescribeLogGroups
                  - logs:CreateLogStream
                  - logs:DescribeLogStreams
                  - logs:PutLogEvents
                Effect: Allow
                Resource:
                  - !Sub 'arn:aws:logs:${AWS::Region}:${AWS::AccountId}:log-group:*'
                Sid: LogAccessPolicy
              - Action:
                  - codecommit:GetTree
                  - codecommit:GetFile
                  - codecommit:BatchGetCommits
                  - codecommit:GetCommit
                  - codecommit:GetCommitHistory
                  - codecommit:GetDifferences
                  - codecommit:GetReferences
                  - codecommit:GetObjectIdentifier
                  - codecommit:BatchGetCommits
                Effect: Allow
                Resource:
                  - !Sub 'arn:aws:codecommit:${AWS::Region}:${AWS::AccountId}:${CodeCommitRepoName}'
                Sid: CodeCommitRead
              - Action:
                  - glue:CreateRegistry
                  - glue:CreateSchema
                  - glue:RegisterSchemaVersion
                  - glue:DeleteSchemaVersions
                  - glue:PutSchemaVersionMetadata
                  - glue:GetDifferences
                  - glue:GetReferences
                  - glue:GetObjectIdentifier
                  - glue:BatchGetCommits
                Effect: Allow
                Resource:
                  - !Sub 'arn:aws:glue:${AWS::Region}:${AWS::AccountId}:registry/*'
                  - !Sub 'arn:aws:glue:${AWS::Region}:${AWS::AccountId}:schema/*'
                Sid: AWSGlueSchemaRegistryAccess
              - Action:
                  - codebuild:StartBuild
                  - codebuild:ListBuildsForProject
                  - codebuild:BatchGetBuilds
                Effect: Allow
                Resource:
                  - !GetAtt CodeBuildProject.Arn
                Sid: CodeBuildStartPolicy
            Version: '2012-10-17'
          PolicyName: !Sub ${AWS::StackName}-codecommit-lambda-trigger
      RoleName: !Sub ${AWS::StackName}-codecommit-lambda-trigger-role
  
  PermissionForCodeCommitToInvokeLambda:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName: !Ref CodeCommitLambdaTrigger
      Principal: codecommit.amazonaws.com
  
  EventRuleLambda:
    Type: AWS::Lambda::Function
    DependsOn: EventRuleLambdaRole
    Properties:
      Code:
        S3Bucket: !Ref S3Bucket
        S3Key: !Ref EventRuleLambdaCodeKey
      Description: Lambda function that will be invoked by EventRule on receiving build notification
      FunctionName: !Sub ${AWS::StackName}-codebuild-notification-lambda
      Handler: lambda_function.lambda_handler
      MemorySize: 128
      Role: !GetAtt EventRuleLambdaRole.Arn
      Runtime: python3.9
      Timeout: 60
      Environment:
        Variables:
          SNSTopicArn: !Ref CodeBuildStatusSNSTopic
          CODE_BUILD_PROJECT: !Ref CodeBuildProject
          MANIFEST_FILE_PATH: !Ref ManifestFilePath
  
  EventRuleLambdaRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Action: sts:AssumeRole
            Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
        Version: '2012-10-17'
      Path: /
      Policies:
        - PolicyDocument:
            Statement:
              - Action:
                  - logs:CreateLogGroup
                Effect: Allow
                Resource:
                  - !Sub 'arn:aws:logs:${AWS::Region}:${AWS::AccountId}:*'
                Sid: LogGroupCreationPolicy
              - Action:
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Effect: Allow
                Resource:
                  - !Sub 'arn:aws:logs:${AWS::Region}:${AWS::AccountId}:log-group:/aws/lambda/${AWS::StackName}-codebuild-notification-lambda:*'
                Sid: LogStreamPolicy
              - Action:
                  - SNS:Publish
                Effect: Allow
                Resource: !Ref CodeBuildStatusSNSTopic
                Sid: SNSTopicAccess
              - Action:
                  - codecommit:GetDifferences
                  - codecommit:GetCommit
                  - codecommit:GetFile
                  - codebuild:BatchGetBuilds
                  - glue:ListSchemaVersions
                  - glue:DeleteSchemaVersions
                Effect: Allow
                Resource: 
                  - !Sub 'arn:aws:codecommit:${AWS::Region}:${AWS::AccountId}:${CodeCommitRepoName}'
                  - !Sub 'arn:aws:codecommit:${AWS::Region}:${AWS::AccountId}:schema/*'
                  - !Sub 'arn:aws:codecommit:${AWS::Region}:${AWS::AccountId}:registry/${GlueSchemaRegistryName}'
                  - !GetAtt CodeBuildProject.Arn
                Sid: AccesstoDeleteSchemaVersion
            Version: '2012-10-17'
          PolicyName: !Sub ${AWS::StackName}-codebuild-notification-lambda
      RoleName: !Sub ${AWS::StackName}-codebuild-notification-lambda-role

  CodeBuildStatusNotificationEventRule: 
    Type: AWS::Events::Rule
    Properties: 
      Description: Event Rule to notifiy CodeBuild build status
      EventPattern: 
        source: 
          - aws.codebuild
        detail-type: 
          - CodeBuild Build State Change
        detail: 
          build-status: 
            - SUCCEEDED
            - FAILED
            - STOPPED
      State: ENABLED
      Targets: 
        - 
          Arn: !GetAtt EventRuleLambda.Arn
          Id: ProcessBuildStatusNotification
          InputTransformer:
            InputPathsMap:
              "build-id" : "$.detail.build-id"
              "build-status" : "$.detail.build-status"
              "project-name" : "$.detail.project-name"
              "repository" : "$.detail.additional-information.source.location"
            InputTemplate: |
                {
                  "build-id": "<build-id>", 
                  "project-name": "<project-name>", 
                  "build-status": "<build-status>",
                  "repository": "<repository>"
                }

  PermissionForEventRuleToInvokeLambda: 
    Type: AWS::Lambda::Permission
    Properties: 
      FunctionName: !GetAtt EventRuleLambda.Arn
      Action: lambda:InvokeFunction
      Principal: events.amazonaws.com
      SourceArn: !GetAtt CodeBuildStatusNotificationEventRule.Arn

  EventTopicPolicy:
    Type: 'AWS::SNS::TopicPolicy'
    Properties:
      PolicyDocument:
        Statement:
          - Effect: Allow
            Principal:
              Service: events.amazonaws.com
            Action: 'sns:Publish'
            Resource: '*'
      Topics:
        - !Ref CodeBuildStatusSNSTopic

  CodeBuildStatusSNSTopic:
    Type: AWS::SNS::Topic
    Properties:
      TopicName: !Ref CodeBuildStateSNSTopicName
      DisplayName: GSR Schema Notification

  SNSSubscription:
    Type: AWS::SNS::Subscription
    Properties:
      Endpoint: !Ref YourEmail
      Protocol: email
      TopicArn: !Ref CodeBuildStatusSNSTopic
Outputs:
  CodeCommitRepositoryCloneUrl:
    Description: CodeCommit repo clone url
    Value: !GetAtt CodeCommitRepo.CloneUrlSsh
  ArtifactName:
    Description: CodeArtifact repo
    Value: !GetAtt CodeArtifactRepository.Name
  SNSTopic:
    Description: SNS Topic
    Value: !GetAtt CodeBuildStatusSNSTopic.TopicName
  CodeBuildStatusEventRule:
    Description: CodeBuild status event rule
    Value: !GetAtt CodeBuildStatusNotificationEventRule.Arn
  EventRuleTargetLambda:
    Description: Lambda triggered by event rule
    Value: !GetAtt EventRuleLambda.Arn
  CodeCommitTargetLambda:
    Description: Lambda triggered by codecommit git push
    Value: !GetAtt CodeCommitLambdaTrigger.Arn
  CodeBuildProjectArn:
    Description: CodeBuild project
    Value: !GetAtt CodeBuildProject.Arn
  GSRName:
    Description: CodeBuild project
    Value: !GetAtt GlueSchemaRegistry.Arn
